@startuml


' --- 前提となる仕様 ----------------------
' - 日時がUNIXエポック(default)である場合は、誕生日を通知しない
' - 基本的にサーバーに参加しているメンバーの誕生日通知を送信可能にできる
' ---------------------------------------

title birthコマンド処理フロー
start

:"初期化処理"を実行;

switch (action)

' 誕生日通知設定リスト表示 -----------------------------------
case ( List )

    :コマンドが実行されたギルドのギルドIDを取得;
    :ギルドIDに一致するメンバー情報リストをguild_memberテーブルから取得;
    :メンバー情報リストから「誕生日が存在するもの」をフィルター;

    if (メンバー情報リストが空) is (はい) then
        :「誕生日通知を登録しているメンバーがいないこと」をメッセージで通知;
    else (いいえ)
        :メンバー情報リストが誕生日の降順になるようにソート;
        :メンバーの誕生日とディスプレイ名のリストをメッセージで通知;
    endif

' 誕生日通知設定登録 -----------------------------------
case ( Signup )
    :コマンドが実行されたギルドのギルドIDを取得;
    :コマンドを実行したメンバーのメンバーIDを取得;
    :ギルドIDとメンバーIDに一致するメンバー情報をguild_memberテーブルから取得;

    if (メンバー情報に誕生日が存在しない) is (はい) then

        :誕生日登録のモーダルを表示;
        :ユーザーが誕生日を入力;
        :ユーザーが「送信」ボタンを押下;
        if (誕生日の入力フォーマットが無効) is (はい) then
            :「誕生日の入力フォーマットが無効であること」をメッセージで通知;
        else (いいえ)
            :guild_memberテーブルのメンバーIDに一致するにメンバーの誕生日を更新;
            :「誕生日通知の登録が完了したこと」をメッセージで通知;
        endif
    else (いいえ)
        :「すでに誕生日通知が登録済であること」をメッセージで通知;
    endif

' 誕生日通知設定解除 -----------------------------------
case ( Reset )
    :コマンドが実行されたギルドのギルドIDを取得;
    :コマンドを実行したメンバーのメンバーIDを取得;
    : ギルドIDとメンバーIDに一致するメンバーの誕生日をguild_memberテーブルから取得;

    if (メンバー情報に誕生日が存在しない) is (はい) then
        :「誕生日が登録されていないこと」をメッセージで通知;
    else (いいえ)
        :誕生日解除の確認メッセージと「解除」ボタンを表示;
        :ユーザーが「解除」ボタンを押下;
        :guild_memberテーブルの誕生日と最終通知日をNULLに更新;
        :誕生日解除の確認メッセージと「解除」ボタンを削除;
        :「誕生日通知が解除されたこと」をメッセージで通知;
    endif

endswitch

stop

@enduml
