@startuml
title 誕生日プッシュ通知の処理フロー
start

:すべてのメンバー情報を含むリストをguild_memberテーブルから取得;

:リストからメンバー情報を一つずつ取り出し、通知処理を実行;

repeat

repeat

repeat

repeat
:メンバーの誕生日を取得;

repeat while (メンバーの誕生日が存在しない) is (はい) not (いいえ)
  :タイムゾーン"Asia/Tokyo"の現在日時を取得;
repeat while (メンバーの最終日時が今年度以降 または メンバーの誕生日が現在の月・日ではない) is (はい) not (いいえ)

  :メンバーのギルドIDからチャンネル情報を取得;
repeat while ("一般"または"general"のチャンネル名が存在しない) is (はい) not (いいえ)

:誕生日のメッセージをメンバーのメンションをつけて、"一般"または"general"のチャンネルに送信;
:誕生日のメッセージにリアクションをつける;
:お祝いメッセージの一例を誕生日のメッセージのリプライとして送信;

:guild_memberテーブルに誕生日を通知したメンバーの最終通知日時を記録;

repeat while (次のメンバー情報が存在する) is (はい) not (いいえ)
stop

@enduml