@startuml

title 誕生日プッシュ通知の処理フロー
start


:DB接続;
:guild_memberテーブル作成を含むDBマイグレーション実行;

' 初期更新処理
:guild_memberテーブルから日時がUNIXエポック以外の
ニックネーム, 誕生日を取得;

:誕生日をもとにcron形式でスケジュールを設定;

:スケジューリング実行;

while (指定した時刻になった) is (はい)
  :メンション付きの誕生日メッセージを通知

  @everyone
  {アバターの埋め込みURL画像},
  @{ニックネーム}の誕生日祝おう！;

  :メッセージに「クラッカー」のリアクションをつける;

  :スレッドに「@{ニックネーム}さん 誕生日おめでとうなのだ！」のメッセージを返信;
endwhile

stop

@enduml
