@startuml
title 誕生日コマンドの共通の処理フロー
start

:DB接続;
:DBマイグレーション実行;

' 初期更新処理

:guildテーブルからギルドIDのリストを取得

（以下、ギルドIDごとに処理を実行する）;

:ギルドIDのリストから次のギルドIDを取得;

while (ギルドIDがある) is (はい)

:ギルドIDごとのguild_memberテーブルの情報を取得;

:ギルドIDに一致するメンバーのDiscord User IDのリストを取得;

:「取得したギルドIDに一致するメンバーのDiscord User ID」と
「guild_memberテーブルのDiscord User ID」のリストを比較;


if (「取得したギルドIDに一致するメンバーのDiscord User ID」と「guild_memberテーブルのDiscord User ID」のリストが全一致 ) is (はい) then
else (いいえ)
    if (「guild_memberテーブル」に存在し、「ギルドIDに一致する」には存在しないDiscord User IDがある) is (はい) then
      :「該当のDiscord User IDを含むメンバー情報」をguild_memberテーブルの行から削除;
    else (いいえ)
    endif

    if (「ギルドIDに一致する」に存在し、「guild_memberテーブル」には存在しないDiscord User IDがある) is (はい) then
      :「該当のDiscord User IDを含む取得したギルドIDに一致するメンバー情報」を取得;
      :メンバーguild_memberテーブルの行に追加;
    else (いいえ)
    endif
endif

:ギルドIDのリストから次のギルドIDを取得;

endwhile (いいえ)

stop

@enduml