@startuml

title 誕生日プッシュ通知の処理フロー
start


:DB接続;
:DBマイグレーション実行;


:guildテーブルからギルドIDのリストを取得

（以下、ギルドIDごとに処理を実行する）;

:ギルドIDのリストから次のギルドIDを取得;

while (ギルドIDがある) is (はい)

    ' 初期更新処理
    :guild_memberテーブルから

    「ギルドIDに一致」し、
    「日時がUNIXエポック以外」の
    メンバーID, ニックネーム, 誕生日を取得;

    :誕生日をもとにcron形式でスケジュールを設定;


:ギルドIDのリストから次のギルドIDを取得;
endwhile

:スケジューリング実行;

while (指定した時刻になった) is (はい)
  :メンション付きの誕生日メッセージを通知

  @everyone
  {アバターの埋め込みURL画像},
  @{Discord User ID}の誕生日祝おう！;

  :メッセージに「クラッカー」のリアクションをつける;

  :スレッドに「@{Discord User ID} {ニックネーム}さん 誕生日おめでとうなのだ！」のメッセージを返信;
endwhile
  -[hidden]->

@enduml
